#! /usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2012 Romain Roffé
#
# This file is part of Todomanager
# 
# Todomanager is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# Todomanager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Todomanager; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

from libtodomanager.todomanager import *
from libtodomanager.persistency.pickleserializer import *
from todomanagercli.shell import *
from todomanagercli.commands import *

FILEPATH = "todolist.bin"

if __name__ == '__main__':
    serializer = PickleSerializer(FILEPATH)

    (res, todo) = serializer.load()
    if res != ErrorCode.kOk:
        print "Starting from empty content"

    todo.setSerializer(serializer)
    sh = Shell(todo)    

    cmdList = [
        CommandPrintTagList(),
        CommandAddTag(),
        CommandPrintOpenedTicketList(),
        CommandOpenTicket(),
        CommandPrintTicket(),
        CommandCloseTicket(),
        CommandAddTagToTicket(),
    ]

    sh.register_command_list(cmdList)
    sh.cmdloop()

